name: Pipeline

on: [push]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Test application
        run: npm run test
      - name: Build for production
        run: npm run build
      - name: setup fly.io cli
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: deploy to fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLYIO_AUTH_TOKEN }}