name: Pipeline

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]
  push:
    branches:
      - "master"

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Test application
        run: npm run test
      - name: Build for production
        run: npm run build
      - name: setup fly.io cli
        if: ${{ github.event_name == 'push' }}
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: deploy to fly.io
        if: ${{ github.event_name == 'push' }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLYIO_AUTH_TOKEN }}

      - name: Log in to Docker Hub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        if: ${{ github.event_name == 'push' }}
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ewintil/pokedex
      
      - name: Build and push Docker image
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  tag_and_realease:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          WITH_V: true